version: '3.8'

services:
  hello-python:
    build:
      context: ./hello-python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - hello-python